version: '3.7'
# nginx, php-fpm, memcached, postgres

services:

    nginx:
        image: nginx:1.17.7
        restart: on-failure
        build: # Configuration options that are applied at build time
            context: # Either a path to a directory containing a Dockerfile, or a url to a git repository.
            dockerfile: Dockerfile
        volumes: # will establish that our local folder called symfony will be linked to the /var/www/symfony folder of the container
            - ./symfony/:/var/www/symfony/
            - ./build/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        ports: # performs mapping between port 80 of the container and port 8001 that we will use to access through the browser
            - 8001:80
        networks:
            - symfony

    php:
        build:
            context: ./build/php-fpm/
            dockerfile: Dockerfile
        restart: on-failure
        environment: # environment variables that we want our Symfony project to read and load later
            APP_ENV: dev
        volumes:
            - ./symfony/:/var/www/symfony/
        networks:
            - symfony
        depends_on:
            - postgres
            - memcached

    memcached:
        image: memcached:1.5.20
        restart: on-failure
        networks:
            - symfony

    postgres:
        image: postgres:12.1
        restart: on-failure
        networks:
            - symfony

networks: # establish a network for the entire project so that all containers can communicate with each other
    symfony:
