version: '3.7'
# nginx, php-fpm, memcached, postgres

services:

    nginx:
        container_name: nginx
        image: nginx:1.17.7
        restart: on-failure
        volumes:
            - ./symfony/:/var/www/symfony/
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - 8001:80
        networks:
            - symfony-network

    php:
        container_name: php
        build: ./docker/php/
        image: php:home
        restart: on-failure
        environment:
            APP_ENV: dev
        volumes:
            - ./symfony/:/var/www/symfony/
        networks:
            - symfony-network
        depends_on:
            - postgres
            - memcached

    memcached:
        container_name: memcached
        image: memcached:1.5.20
        restart: on-failure
        networks:
            - symfony-network

    postgres:
        container_name: postgres
        build: ./docker/postgres/
        image: postgres:home
        restart: on-failure
        ports:
          - '5000:5432'
        environment:
          - POSTGRES_PASSWORD=secret1S # superuser password
        networks:
            - symfony-network

networks:
    symfony-network:
      name: symfony-network
